<a href="https://colab.research.google.com/github/mohammedhelalu/Emploees/blob/master/broadcastingmm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [16]:
myarray3=np.array([[11,22,33,44,55],[66,77,88,99,100]])

In [17]:
myarray4=np.array([11,22,33,44,55])

In [18]:
myarray_total3 = myarray3 + myarray4 

In [19]:
print(myarray_total3)

[[ 22  44  66  88 110]
 [ 77  99 121 143 155]]


In [20]:
myarray_total3 = myarray3 * myarray4 

In [21]:
print(myarray_total3)

[[ 121  484 1089 1936 3025]
 [ 726 1694 2904 4356 5500]]
