<a href="https://colab.research.google.com/github/mohammedhelalu/Emploees/blob/master/Copy_of_zeros%26onesmm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.zeros((3,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
myarray=np.zeros((3,2),dtype=int)

In [ ]:
print(myarray)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
myarray2=np.ones((4,3),dtype=int)

In [ ]:
print(myarray2)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
myarray3=np.empty((3,3),dtype=int)

In [ ]:
print(myarray3)

[[           25497152                  36                   0]
 [                  0        472446402560 4063427976458941029]
 [7148388422076675885 3256441619971138873 3833743304625304884]]
