<a href="https://colab.research.google.com/github/mohammedhelalu/Emploees/blob/master/Functions_eyemm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
 import numpy as np
import numpy.matlib 

In [3]:
myeyearray=np.matlib.eye(4,k=0,dtype=float)

In [4]:
myeyearray

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [5]:
myeyearray=np.matlib.eye(5,k=0,dtype=int)

In [9]:
myeyearray

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [13]:
myeyearray1=np.matlib. identity(5,int)

In [14]:
myeyearray1

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])