<a href="https://colab.research.google.com/github/mohammedhelalu/Emploees/blob/master/functions_mm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
 import numpy as np

In [5]:
myarray=[0.11,2.55,4.88,6.34]

In [6]:
myarray

[0.11, 2.55, 4.88, 6.34]

In [7]:
myarray2=np.ceil(myarray)

In [8]:
myarray2

array([1., 3., 5., 7.])

In [9]:
myarray3=[100.2,32.0095,54.18,77.34]

In [10]:
myarray3

[100.2, 32.0095, 54.18, 77.34]

In [11]:
myarray4=np.ceil(myarray3)

In [12]:
myarray4

array([101.,  33.,  55.,  78.])

In [13]:
myarray5=[10.2,3.95,4.18,7.34]

In [14]:
myarray6=np.fix(myarray5)

In [15]:
myarray6

array([10.,  3.,  4.,  7.])

In [16]:
myarray7=np.floor(myarray5)

In [17]:
myarray7

array([10.,  3.,  4.,  7.])

In [18]:

int_array=[10.6,3.95,4.68,7.884]

In [19]:
int_array2=[10.2,3.45,4.18,7.34]

In [21]:
myarray_total=np.rint(int_array)

In [22]:
myarray_total2=np.rint(int_array2)

In [23]:
int_array
myarray_total


array([11.,  4.,  5.,  8.])

In [24]:
int_array2
myarray_total2

array([10.,  3.,  4.,  7.])