<a href="https://colab.research.google.com/github/mohammedhelalu/Emploees/blob/master/nparray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([11,22,33])

In [3]:
print(a)

[11 22 33 44 55]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
b = np.array([[11,22,33,44,55],[1,2,3,4,5]])

In [6]:
print(b)

[[11 22 33 44 55]
 [ 1  2  3  4  5]]


In [7]:
c = np.array([77,12,44,25],complex)

In [8]:
print(c)

[77.+0.j 12.+0.j 44.+0.j 25.+0.j]


In [9]:
print(c.ndim)

1


In [10]:
print(b.ndim)

2


In [11]:
print(c.itemsize)

16


In [12]:
print(b.itemsize)

8


In [13]:
print(a)

[11 22 33 44 55]


In [14]:
print(a.dtype)

int64


In [15]:
print(a)

[11 22 33 44 55]


In [16]:
print(a.size)

5


In [17]:
print(b.size)

10


In [18]:
print(b.shape)

(2, 5)


In [19]:
print(a.shape)

(5,)
