<a href="https://colab.research.google.com/github/mohammedhelalu/Emploees/blob/master/structured_arraymm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
 import numpy as np

In [38]:
employee_info=[("name","S10"),("salary","f8"),("age","i8")]

In [39]:
print(employee_info)

[('name', 'S10'), ('salary', 'f8'), ('age', 'i8')]


In [40]:
emmployees_staff=np.zeros((3),dtype=employee_info)

In [41]:
print(emmployees_staff)

[(b'', 0., 0) (b'', 0., 0) (b'', 0., 0)]


In [42]:
emmployees_staff

array([(b'', 0., 0), (b'', 0., 0), (b'', 0., 0)],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [43]:
emmployees_staff[1]=("mohammed",6000,52)

In [44]:
emmployees_staff[2]=("ahmed",4000,42)

In [45]:
emmployees_staff

array([(b'',    0.,  0), (b'mohammed', 6000., 52), (b'ahmed', 4000., 42)],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [46]:
emmployees_staff[0:]

array([(b'',    0.,  0), (b'mohammed', 6000., 52), (b'ahmed', 4000., 42)],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [47]:
emmployees_staff[1:]

array([(b'mohammed', 6000., 52), (b'ahmed', 4000., 42)],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [48]:
salary=emmployees_staff["salary"]

In [49]:
emmployees_staff["age"]

array([ 0, 52, 42])

In [50]:
add_salary=salary+2000

In [51]:
add_salary

array([2000., 8000., 6000.])

In [52]:
age=emmployees_staff["age"]

In [53]:
add_age=age+3

In [54]:
add_age

array([ 3, 55, 45])

In [55]:
emmployees_staff

array([(b'',    0.,  0), (b'mohammed', 6000., 52), (b'ahmed', 4000., 42)],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [56]:
all_employees_staff=np.zeros((4,3,2),dtype=employee_info)

In [57]:
all_employees_staff

array([[[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]],

       [[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]],

       [[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]],

       [[(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)],
        [(b'', 0., 0), (b'', 0., 0)]]],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [58]:
all_employees_staff["name"]

array([[[b'', b''],
        [b'', b''],
        [b'', b'']],

       [[b'', b''],
        [b'', b''],
        [b'', b'']],

       [[b'', b''],
        [b'', b''],
        [b'', b'']],

       [[b'', b''],
        [b'', b''],
        [b'', b'']]], dtype='|S10')

In [59]:
all_employees_staff["age"]

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [60]:
all_employees_staff["salary"]

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [61]:
all_employees_staff[0,0,1]=("mohammed",5000,54)

In [62]:
all_employees_staff

array([[[(b'',    0.,  0), (b'mohammed', 5000., 54)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]]],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [63]:
all_employees_staff[1,1,0]=("Helal",4000,44)

In [64]:
all_employees_staff

array([[[(b'',    0.,  0), (b'mohammed', 5000., 54)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'Helal', 4000., 44), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]]],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [65]:
all_employees_staff[3,2,1]=("ahmed",2000,34)

In [66]:
all_employees_staff

array([[[(b'',    0.,  0), (b'mohammed', 5000., 54)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'Helal', 4000., 44), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)]],

       [[(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'',    0.,  0)],
        [(b'',    0.,  0), (b'ahmed', 2000., 34)]]],
      dtype=[('name', 'S10'), ('salary', '<f8'), ('age', '<i8')])

In [68]:
all_employees_staff["name"]

array([[[b'', b'mohammed'],
        [b'', b''],
        [b'', b'']],

       [[b'', b''],
        [b'Helal', b''],
        [b'', b'']],

       [[b'', b''],
        [b'', b''],
        [b'', b'']],

       [[b'', b''],
        [b'', b''],
        [b'', b'ahmed']]], dtype='|S10')

In [69]:
all_employees_staff["salary"]

array([[[   0., 5000.],
        [   0.,    0.],
        [   0.,    0.]],

       [[   0.,    0.],
        [4000.,    0.],
        [   0.,    0.]],

       [[   0.,    0.],
        [   0.,    0.],
        [   0.,    0.]],

       [[   0.,    0.],
        [   0.,    0.],
        [   0., 2000.]]])

In [70]:
all_employees_staff["age"]

array([[[ 0, 54],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [44,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0, 34]]])

In [71]:
all_employees_staff[["name","age"]]

array([[[(b'',  0), (b'mohammed', 54)],
        [(b'',  0), (b'',  0)],
        [(b'',  0), (b'',  0)]],

       [[(b'',  0), (b'',  0)],
        [(b'Helal', 44), (b'',  0)],
        [(b'',  0), (b'',  0)]],

       [[(b'',  0), (b'',  0)],
        [(b'',  0), (b'',  0)],
        [(b'',  0), (b'',  0)]],

       [[(b'',  0), (b'',  0)],
        [(b'',  0), (b'',  0)],
        [(b'',  0), (b'ahmed', 34)]]],
      dtype={'names':['name','age'], 'formats':['S10','<i8'], 'offsets':[0,18], 'itemsize':26})

In [72]:
all_employees_staff[["name","salary"]]

array([[[(b'',    0.), (b'mohammed', 5000.)],
        [(b'',    0.), (b'',    0.)],
        [(b'',    0.), (b'',    0.)]],

       [[(b'',    0.), (b'',    0.)],
        [(b'Helal', 4000.), (b'',    0.)],
        [(b'',    0.), (b'',    0.)]],

       [[(b'',    0.), (b'',    0.)],
        [(b'',    0.), (b'',    0.)],
        [(b'',    0.), (b'',    0.)]],

       [[(b'',    0.), (b'',    0.)],
        [(b'',    0.), (b'',    0.)],
        [(b'',    0.), (b'ahmed', 2000.)]]],
      dtype={'names':['name','salary'], 'formats':['S10','<f8'], 'offsets':[0,10], 'itemsize':26})